pipeline:
  - lint
  - mypy

jobs:
  lint:
    architectures: amd64
    packages:
      - tox
      - git
    snaps:
      - name: go
        classic: true
    run: tox -e lint
    series: focal
  mypy:
    architectures: amd64
    packages:
      - tox
    run: tox -e mypy
    series: focal
