#! /usr/bin/python3 -S
#
# Copyright 2023 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

import _pythonpath  # noqa: F401

from lp.scripts.utilities.anointteammember import AnointTeamMemberScript

if __name__ == "__main__":
    AnointTeamMemberScript("anoint-team-member", dbuser="launchpad").run()
