#!/usr/bin/python3
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Update the sourcecode managed in sourcecode/.

This script is now a no-op, and will be removed once no deployment machinery
uses it any more.
"""

import sys

if __name__ == "__main__":
    sys.exit(0)
