options:
  bing_custom_config_id:
    type: string
    description: Identifier for the Bing Custom Search instance.
    default:
  bing_custom_search_endpoint:
    type: string
    description: The endpoint to send the Bing custom search requests to.
    default: "https://api.bing.microsoft.com/v7.0/custom/search"
  bing_subscription_key:
    type: string
    description: >
      Cognitive Services subscription key for the Bing Custom Search API.
    default:
  blocked_user_agents:
    type: string
    description: >
      User agents that should be blocked from Launchpad, separated by '|'.
    default:
  csrf_secret:
    type: string
    description: >
      Secret used to create CSRF tokens.  Currently only used in Candid
      interactions.
    default:
  devmode:
    type: boolean
    description: Is this server running in dev mode?
    default: true
  git_macaroon_secret_key:
    type: string
    description: >
      Secret key for Git access tokens issued to Launchpad users.  Any
      random string of a reasonable size (64 characters) is ok.
    default:
  google_site_verification:
    type: string
    description: >
      If set, serve a /google{...} URL that can be used to verify domain
      ownership.
    default: ""
  haproxy_server_options:
    type: string
    description: Options to add to HAProxy "server" lines.
    default: check inter 5000 rise 2 fall 5 maxconn 16
  haproxy_service_options_main:
    type: string
    description: HAProxy options for the main port.
    default: |
      - mode http
      - option httplog
      - option httpchk HEAD /_status/ping
      - option http-server-close
      - option forwardfor
      - http-check disable-on-404
      - balance roundrobin
  haproxy_service_options_xmlrpc:
    type: string
    description: HAProxy options for the XML-RPC port.
    default: |
      - mode http
      - option httplog
      - option httpchk HEAD /_status/ping
      - option http-server-close
      - option forwardfor
      - http-check disable-on-404
      - balance roundrobin
  internal_bzr_codebrowse_endpoint:
    type: string
    description: The URL of the internal Bazaar code browsing endpoint.
    default: ""
  internal_macaroon_secret_key:
    type: string
    description: >
      Secret key for macaroons used to grant permissions to various internal
      components of Launchpad.  Any random string of a reasonable size (64
      characters) is ok.
    default:
  logrotate_frequency:
    type: string
    description: Frequency of logrotate (daily or hourly)
    default: daily
  mailman_archive_url_template:
    type: string
    description: Template expanded to form URLs for Launchpad list archives.
    default: "http://lists.launchpad.test/$team_name"
  min_legitimate_account_age:
    type: int
    description: Minimum account age in days that indicates a legitimate user.
    default:
  min_legitimate_karma:
    type: int
    description: Minimum karma value that indicates a legitimate user.
    default:
  port_main:
    type: int
    description: Port for the main application server.
    default: 8085
  port_main_cached:
    type: int
    description: Port for the main application server via Squid.
    default: 8086
  ssl_chain_required:
    type: boolean
    description: >
      Whether an intermediate certificate chain is needed for this service.
      In development, we use self-signed certificates which don't have a
      certificate chain; but in real deployments, we need to send a
      certificate chain.
    default: false
  webmaster_email:
    type: string
    description: Email address to include in Apache virtual host configuration.
    default: "webmaster@launchpad.test"
  wsgi_worker_max_requests:
    type: int
    description: >
      Restart WSGI worker processes after handling this many requests.  This
      works around memory leaks.
    default: 1000
  wsgi_workers:
    type: int
    default: 0
    description: >
      The number of worker processes for handling requests.
      The default is 0, indicating twice the number of CPUs plus one.
