options:
  active:
    type: boolean
    default: true
    description: If true, enable jobs that may change the database.
  artifactory_base_url:
    type: string
    default:
    description:
      Base URL for publishing suitably-configured archives to Artifactory.
  artifactory_write_credentials:
    type: string
    default:
    description: >
      Credentials for writing to Artifactory repositories (formatted as
      "user:token").
  domain_ppa_private:
    type: string
    default: private-ppa.launchpad.test
    description: |
      Domain for private PPA requests.
  domain_ppa_private_alt:
    type: string
    default:
    description: |
      If set, the requests to this alternative domain will also be allowed for
      accessing private PPAs.
  domain_ppa_public:
    type: string
    default: ppa.launchpad.test
    description: |
      Domain for public PPA requests.
  domain_ppa_public_alt:
    type: string
    default:
    description: |
      If set, the requests to this alternative domain will also be allowed for
      accessing public PPAs.
  domain_ppa_buildd:
    type: string
    default:
    description: Domain for PPA buildd route.
  logparser_max_parsed_lines:
    type: int
    default: 10000000
    description: > 
      The maximum number of lines that should be parsed by the launchpad log
      parser.
  oval_data_rsync_endpoint:
    type: string
    default:
    description: If set, use as rsync endpoint for synchronizing the OVAL data.
  ppa_update_keys_script_archives_limit:
    type: int
    default: 1000
    description: |
      The number of affected PPAs that the ppa-update-keys.py cron script should
      process in a single run.
  parallel_publisher_config:
    type: string
    description: |
      YAML-encoded config that lists the excluded PPAs and configurations
      for parallel publisher runs. Example:
      parallel_publisher_config:
        excluded_ppas:
          - foo/ubuntu/ppa1
          - foo/ubuntu/ppa2
          - foo/ubuntu/ppa5
          - foo/debian/ppa3
          - foo/soss/ppa4
        runs:
          - distro: ubuntu
            id: parallel-run-1
            ppas:
              - foo/ubuntu/ppa1
          - distro: ubuntu
            id: parallel-run-2
            ppas:
              - foo/ubuntu/ppa2
              - foo/ubuntu/ppa5
          - distro: debian
            id: parallel-run-3
            ppas:
              - foo/debian/ppa3
          - distro: all_derived
            id: parallel-run-4
            ppas:
              - foo/soss/ppa4
    default: ""
  require_signing_keys:
    type: boolean
    description: > 
      If true, PPAs and copy archives will only be published once their
      signing-keys have been generated.
    default: False
  signing_client_private_key:
    type: string
    description: >
      Private key for encrypting communication between client and signing
      service. 
    default: ""
  signing_client_public_key:
    type: string
    description: >
      Public key for encrypting communication between client and signing
      service. 
    default: ""
  signing_endpoint:
    type: string
    default:
    description: Endpoint for the signing service.
